# Site settings
title: Cohitre
email: carlosrr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  cohitre stories, comics, fun and art.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cohitre.com" # the base hostname & protocol for your site
twitter_username: cohitre
github_username:  cohitre

# Build settings
markdown: kramdown
